SELECT DEMANDEUR.nom, DEMANDELOGEMENT.dateDemande
FROM DEMANDEUR, DEMANDELOGEMENT, SECTEURDEMANDE
WHERE DEMANDEUR.id = DEMANDELOGEMENT.id
AND SECTEURDEMANDE.id  = DEMANDELOGEMENT.id
AND SECTEURDEMANDE.nom = 'Loire-Sud'