SELECT MODELEAUTO.LibelléModèle, SUM(MttTotalCotisation) / SUM(CumulCoûtSinistre) As Ratio
FROM MODELEAUTO, STATISTIQUEMODEL
WHERE MODELEAUTO.CodeModèle = STATISTIQUEMODEL.CodeModèle
AND STATISTIQUEMODELE.Année = '2012'
GROUP BY MODELEAUTO.LibelléModèle
HAVING Ratio > 4 ;