SELECT MODELEAUTO CodeModèle, MODELEAUTO.LibelléModèle, MODELEAUTO.LibelléMarque, STATISTIQUEMODELE.Année, SUM(NbSinistre), SUM(CumulCoûtSinistre), SUM(MttTotalCotisation)
FROM MODELEAUTO, STATISTIQUEMODEL
WHERE MODELEAUTO.CodeModèle = STATISTIQUEMODEL.CodeModèle
GROUP BY MODELEAUTO.CodeModèle, MODELEAUTO.LibelléModèle, MODELEAUTO.LibelléMarque, STATISTIQUEMODELE.Année ;