SELECT TRIATHLETE.NomAthlete, TRIATHLETE.PrenomAthlete
FROM PISCINE, ENTRAINEMENT, PLAN_ENTRAINEMENT, TRIATHLETE
WHERE PISCINE.NumPiscine = ENTRAINEMENT.NumPiscine
AND ENTRAINEMENT.NumEntrainement = PLAN_ENTRAINEMENT.NumEntrainement
AND TRIATHLETE.NumLicense = PLAN_ENTRAINEMENT.NumLicense
AND TRIATHLETE.CategorieAthlete = 'Minime'
AND PLAN_ENTRAINEMENT.DistanceParcourue Is NULL
AND DateEntrainement = '2013-09-12'
AND HeureDebut = '20H'
AND NomPiscine = 'KIKI CARON' ;